// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz6mSq05bT2Hbvn2W0q3B_8xkMct8UuOU',
    appId: '1:922953431526:android:cf2d977acd4b41edf8fe27',
    messagingSenderId: '922953431526',
    projectId: 'heaven-on-this-e-1673398261366',
    storageBucket: 'heaven-on-this-e-1673398261366.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcS3P7dqPzBqiEDWRhVg_3WGckQPsmewA',
    appId: '1:922953431526:ios:7d4921b1105398e8f8fe27',
    messagingSenderId: '922953431526',
    projectId: 'heaven-on-this-e-1673398261366',
    storageBucket: 'heaven-on-this-e-1673398261366.appspot.com',
    androidClientId: '922953431526-cum1u30k58om3it9vu4grd3khup32hcc.apps.googleusercontent.com',
    iosClientId: '922953431526-3aau5t8378moj3d2lr7l005gi5neq3l5.apps.googleusercontent.com',
    iosBundleId: 'com.starwish.storyImageAi',
  );

}